package com.dao.mapper;

import com.dao.model.LCContChange;

public interface LCContChangeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lccontchange
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String edoracceptno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lccontchange
     *
     * @mbggenerated
     */
    int insert(LCContChange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lccontchange
     *
     * @mbggenerated
     */
    int insertSelective(LCContChange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lccontchange
     *
     * @mbggenerated
     */
    LCContChange selectByPrimaryKey(String edoracceptno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lccontchange
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(LCContChange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lccontchange
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(LCContChange record);
}