package com.dao.mapper;

import com.dao.model.PrintTableConfig;

public interface PrintTableConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table print_table_config
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table print_table_config
     *
     * @mbggenerated
     */
    int insert(PrintTableConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table print_table_config
     *
     * @mbggenerated
     */
    int insertSelective(PrintTableConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table print_table_config
     *
     * @mbggenerated
     */
    PrintTableConfig selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table print_table_config
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PrintTableConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table print_table_config
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PrintTableConfig record);
}