package com.dao.model;

public class EdorApplyInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edor_apply_info.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edor_apply_info.ApplyIDType
     *
     * @mbggenerated
     */
    private String applyidtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edor_apply_info.ApplyIDNo
     *
     * @mbggenerated
     */
    private String applyidno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edor_apply_info.ApplyName
     *
     * @mbggenerated
     */
    private String applyname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edor_apply_info.ID
     *
     * @return the value of edor_apply_info.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edor_apply_info.ID
     *
     * @param id the value for edor_apply_info.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edor_apply_info.ApplyIDType
     *
     * @return the value of edor_apply_info.ApplyIDType
     *
     * @mbggenerated
     */
    public String getApplyidtype() {
        return applyidtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edor_apply_info.ApplyIDType
     *
     * @param applyidtype the value for edor_apply_info.ApplyIDType
     *
     * @mbggenerated
     */
    public void setApplyidtype(String applyidtype) {
        this.applyidtype = applyidtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edor_apply_info.ApplyIDNo
     *
     * @return the value of edor_apply_info.ApplyIDNo
     *
     * @mbggenerated
     */
    public String getApplyidno() {
        return applyidno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edor_apply_info.ApplyIDNo
     *
     * @param applyidno the value for edor_apply_info.ApplyIDNo
     *
     * @mbggenerated
     */
    public void setApplyidno(String applyidno) {
        this.applyidno = applyidno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edor_apply_info.ApplyName
     *
     * @return the value of edor_apply_info.ApplyName
     *
     * @mbggenerated
     */
    public String getApplyname() {
        return applyname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edor_apply_info.ApplyName
     *
     * @param applyname the value for edor_apply_info.ApplyName
     *
     * @mbggenerated
     */
    public void setApplyname(String applyname) {
        this.applyname = applyname;
    }
}