package com.dao.model;

public class TableConfi {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pe_table_config.Id
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pe_table_config.MAINTABLE
	 * @mbggenerated
	 */
	private String maintable;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pe_table_config.RELATABLE
	 * @mbggenerated
	 */
	private String relatable;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pe_table_config.CONNECTTYPE
	 * @mbggenerated
	 */
	private String connecttype;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pe_table_config.CONNECTCONDITION
	 * @mbggenerated
	 */
	private String connectcondition;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pe_table_config.querycontidion
	 * @mbggenerated
	 */
	private String querycontidion;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pe_table_config.Id
	 * @return  the value of pe_table_config.Id
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pe_table_config.Id
	 * @param id  the value for pe_table_config.Id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pe_table_config.MAINTABLE
	 * @return  the value of pe_table_config.MAINTABLE
	 * @mbggenerated
	 */
	public String getMaintable() {
		return maintable;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pe_table_config.MAINTABLE
	 * @param maintable  the value for pe_table_config.MAINTABLE
	 * @mbggenerated
	 */
	public void setMaintable(String maintable) {
		this.maintable = maintable;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pe_table_config.RELATABLE
	 * @return  the value of pe_table_config.RELATABLE
	 * @mbggenerated
	 */
	public String getRelatable() {
		return relatable;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pe_table_config.RELATABLE
	 * @param relatable  the value for pe_table_config.RELATABLE
	 * @mbggenerated
	 */
	public void setRelatable(String relatable) {
		this.relatable = relatable;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pe_table_config.CONNECTTYPE
	 * @return  the value of pe_table_config.CONNECTTYPE
	 * @mbggenerated
	 */
	public String getConnecttype() {
		return connecttype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pe_table_config.CONNECTTYPE
	 * @param connecttype  the value for pe_table_config.CONNECTTYPE
	 * @mbggenerated
	 */
	public void setConnecttype(String connecttype) {
		this.connecttype = connecttype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pe_table_config.CONNECTCONDITION
	 * @return  the value of pe_table_config.CONNECTCONDITION
	 * @mbggenerated
	 */
	public String getConnectcondition() {
		return connectcondition;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pe_table_config.CONNECTCONDITION
	 * @param connectcondition  the value for pe_table_config.CONNECTCONDITION
	 * @mbggenerated
	 */
	public void setConnectcondition(String connectcondition) {
		this.connectcondition = connectcondition;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pe_table_config.querycontidion
	 * @return  the value of pe_table_config.querycontidion
	 * @mbggenerated
	 */
	public String getQuerycontidion() {
		return querycontidion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pe_table_config.querycontidion
	 * @param querycontidion  the value for pe_table_config.querycontidion
	 * @mbggenerated
	 */
	public void setQuerycontidion(String querycontidion) {
		this.querycontidion = querycontidion;
	}
}